djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),  # so wird die HomeApp als startcscreen verwendet



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from . import views
from .views import HomeView, RegisterView, UserLoginView, ProfileView, SettingsView, PictureDetailView, logout_view, \
    UsersImagesListView, UserAddPictureView, PictureUpdateView, CustomerDetailView, CategoryView, \
    SearchResultView, CustomerProfileView, SingleCategoryView, ExploreListView

app_name = 'home'
urlpatterns = [

                  # HOMEVIEW
                  path('', HomeView.as_view(), name='index'),

                  # DESCRIPTION PAGES
                  # Description (whats going on this website?)
                  path('description/', TemplateView.as_view(template_name='home/description.html'), name='description'),

                  # SIGN IN / SIGN UP / SIGN OUT
                  # Sign In
                  path('login/', UserLoginView.as_view(), name='login'),

                  # Sign Up
                  path('register/', RegisterView.as_view(), name='register'),

                  # logout
                  path('logout/', logout_view, name='logout'),

                  # CATEGORY VIEWS
                  # Graphic
                  path('categories/', CategoryView.as_view(), name='category'),

                  # Search View SearchResultView
                  path('search/', SearchResultView.as_view(), name='search'),

                  # VIEWS FOR SINGLE CATEGORY
                  # Graphic, Explore

                  path('explore/', ExploreListView.as_view(), name="explore_view"),

                  path('category/<slug:slug>/', SingleCategoryView.as_view(), name='category_single'),

                  # Picture DETAIL VIEW
                  path('image/<slug:slug>', CustomerDetailView.as_view(), name='customer_detail_view'),

                  # MY-IMAGES VIEW
                  # Graphic and Picture ListView
                  path('my-images/', UsersImagesListView.as_view(), name='my-images'),

                  # Graphic and Picture detail
                  path('user-picture/<int:pk>/<slug:slug>/', PictureDetailView.as_view(), name='user-picture'),

                  # UPDATE VIEW
                  path('edit-image/<int:pk>/<slug:slug>/', PictureUpdateView.as_view(), name='edit-image'),

                    # CUSTOMER PROFILE VIEW
                    path('user/<int:pk>/<slug:slug>/', CustomerProfileView.as_view(), name='customer_profile_view'),




                  # DELETE VIEW
                 # path('delete/<int:pk>/', views.delete_object_view, name='delete'),

                  # CREATE VIEW
                  path('create/', UserAddPictureView.as_view(), name='create'),
                  # Todo Graphic #

                  # PROFILE AND SETTINGS
                  # Profile
                  path('profile/<int:pk>/', ProfileView.as_view(), name="profile"),

                  # Settings
                  path('settings/', SettingsView.as_view(), name='settings'),

                  # for media and static load
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
import random

from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator, FileExtensionValidator, DecimalValidator
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from djangoProject.settings import MEDIA_URL, STATIC_URL, BASE_DIR
from django.contrib.auth.models import AbstractUser


#####################    AUTHENTICATION MODEL    #####################

class User(AbstractUser):
    profile_image = models.ImageField(
        default='media/user_img_default.png',
        blank=True,
        null=True,
        upload_to='media',
        validators=[FileExtensionValidator(
            allowed_extensions=['jpg', 'jpeg', 'png']
        )
        ]
    )
    password2 = models.CharField(
        max_length=32,
        default=''
    )
    date_created = models.DateTimeField(
        auto_now_add=True
    )
    slug = models.SlugField(
        max_length=100,
        default=''
    )

    def __str__(self):
        return f' {self.username} {self.password} {self.email} {self.date_created}'

    def get_absolute_url(self):  # self.title wird als absoluter url returnt
        return reverse("home:profile")


'''
class ImageUpload(models.Model):
    class ImageType(models.TextChoices):
        PICTURE = 'Picture' 'Picture'
        GRAPHIC = 'Graphic' 'Graphic'
        VIDEO = 'Video' 'Video'

    base_role = ImageType.PICTURE

    image_type = models.CharField(
        default='Picture',
        max_length=50,
        choices=ImageType.choices,
    )

    def save(self, *args, **kwargs):
        if len(self.image_type) <= 4:
            self.role = self.base_role
            return super().save(*args, **kwargs)





'''


#########################        DATA UPLOAD MODELS        #########################
# CATEGORIES #
class PictureCategories(models.Model):
    name = models.CharField(
        max_length=100,
        db_index=True
    )
    p_cat_picture = models.ImageField(
        error_messages={'required': 'Load min 1 Graphic ...'},
        upload_to='media',
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]
    )
    slug = models.SlugField(
        max_length=100,
        unique=True
    )

    class Meta:
        verbose_name_plural = 'p_categories'
        ordering = ['name']  # this sort the category names form a-z. if you want to sort by z-a than just write a
        # comma before

    def __str__(self):
        return self.name

    def get_absolute_url(self):  # self.title wird als absoluter url returnt
        return reverse("home:category_single", kwargs={"slug": self.slug})

    def get_url_to_single(self):
        return reverse("home:customer_detail_view", kwargs={"slug": self.slug})


class GraphicCategory(models.Model):
    name = models.CharField(
        max_length=100,
        db_index=True  # stellt einen index für den namen, sodass bei einer abfrage nciht jedes Mal die gesammte db
        # durchlaufen werden muss, wenn eine Anfrage gesendet wird
    )
    g_cat_picture = models.ImageField(
        error_messages={'required': 'Load min 1 Graphic ...'},
        upload_to='media',
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]
    )
    slug = models.SlugField(
        max_length=100,
        unique=True  # jeder slug darf nur einmal vorkommen
    )

    class Meta:
        verbose_name_plural = 'g_categories'
        # für instructions (für django)
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):  # self.title wird als absoluter url returnt

        return reverse("home:category_single", kwargs={"slug": self.slug})

    def get_url_to_single(self):
        return reverse("home:customer_g_view")


# UPLOAD MEDIA #

class UserAddPicture(models.Model):  # User Create new Picture

    title = models.CharField(  # der title wird im url dargestellt
        error_messages={'required': 'Title is required'},
        max_length=100
    )
    picture = models.ImageField(
        error_messages={'required': 'Load min. 1 Picture ...'},
        upload_to='media',
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]
    )  # mit FileExtensioValidator können die erlaubten dateiformate festgelegt werden.
    category = models.ForeignKey(
        PictureCategories,
        max_length=100,
        default='Category',
        related_name='picture',  # erklärung im GraphicsUpload model
        on_delete=models.CASCADE
    )

    tag_field = TaggableManager(
        blank=True,
        help_text='Choose some tags that people can find your Picture ...'
    )
    user_name = models.ForeignKey(
        User,
        on_delete=models.CASCADE,  # 1 insanz der klasse wird gespeichert
        related_name='user_name'  # so kann im Template einfacher auf den user zugegeriffen werden.
    )

    date = models.DateTimeField(
        auto_now_add=True
    )
    slug = models.SlugField(
        unique=True,
        max_length=100
    )
    is_active = models.BooleanField(
        default=True
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        verbose_name_plural = 'picture'
        ordering = ['-date']  # wonach die Bilder geordnet werden sollen...

    def __str__(self):
        return f' {self.title}' \
               f' {self.picture}' \
               f' {self.tag_field}' \
               f' {self.user_name} ' \
               f' {self.date}'  # 1 jetzt kann jeder in der klasse definierter Wert über die return funktion abgerufen werden

    def get_absolute_url(self):  # self.title wird als absoluter url returnt
        # mit self.pk wird die id der instanz automatisch hinzugefügt
        return reverse("home:customer_detail_view", kwargs={"slug": self.slug})

    def get_user_detail_url(self):
        return reverse("home:user-picture", kwargs={"pk": self.pk, "slug": self.slug})

    def get_absolute_customer_detail_url(self):
        return reverse("home:customer_detail_view", kwargs={"slug": self.slug})


################################

class GraphicUpload(models.Model):
    title = models.CharField(  # der title wird im url dargestellt
        error_messages={'required': 'Title is required'},
        max_length=100
    )
    picture = models.ImageField(
        error_messages={'required': 'Load min 1 Graphic ...'},
        upload_to='media',
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]
    )  # mit FileExtensioValidator können die erlaubten dateiformate festgelegt werden.
    category = models.ForeignKey(
        GraphicCategory,
        max_length=100,
        default='Category',
        related_name='graphic_category',
        # wird für den zugriff in zB views oder im template verwendet: Bsp: Model.graphics.all() statt Model.objects.all()
        on_delete=models.CASCADE
    )

    tag_field = TaggableManager(
        help_text='Choose some tags that people can find your Graphic ...'
    )
    g_username = models.ForeignKey(
        User,
        related_name='g_username',
        on_delete=models.CASCADE,  # wird der user gelöscht ird auh das produkt gelöscht
    )
    date = models.DateTimeField(
        auto_now_add=True
    )
    slug = models.SlugField(
        unique=True,
        max_length=100,
    )
    is_active = models.BooleanField(
        default=True
    )
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'graphics_upload'
        ordering = ['-date']  # wonach die graphic-Bilder geordnet werden sollen...

    def __str__(self):
        return f' {self.title}' \
               f' {self.picture}' \
               f' {self.tag_field}' \
               f' {self.g_username} ' \
               f' {self.date}'  # 1 jetzt kann jeder in der klasse definierter Wert über die return funktion abgerufen werden
        #        f'{self.currency}' \ später mit currency auswahl

    def get_absolute_url(self):  # self.title wird als absoluter url returnt
        # mit self.pk wird die id der instanz automatisch hinzugefügt
        return reverse("home:customer_detail_view", kwargs={"slug": self.slug})

    def get_edit_url(self):
        return reverse('home:edit-image', kwargs={"pk": self.pk, "slug": self.slug})

    def get_user_detail_url(self):
        return reverse("home:user-picture", kwargs={"pk": self.pk, "slug": self.slug})


#############################################


class LoadVideoForPageCreation(models.Model):  # the model to load videos on the homepage
    video = models.FileField(upload_to='media')  # same like models.URLField()


class ProfileImage(models.Model):
    profile_image = models.ImageField()


'''
class RecipeValueIngredients(models.Model):
    value = models.IntegerField(default=100)
    ingredients = models.TextField(default='', max_length=5000)

    class UnityChoices(models.TextChoices):  # um ein choicefiled(dropdownmenu mit verschiedenen auswahlmögl.)= zu erstellen, wird die Klasse textchoices verwendet
        GRAMM = 'g', 'Gramm'  # dieser klasse wird pro vairable ein tupel mit insgesammt 2 werten zugewiesen. der erste wert ist der in welcgher der zweite gespeichert wird.
        KILOGRAMM = 'kg', 'Kilogramm'  # der zweite Wert ist der, der dem Nutzer angezeigt wird.
        MILLILITER = 'ml', 'Milliliter'
        LITER = 'l', 'Liter'
        PINCH = 'p', 'Pinch'

    currency_choice_field = models.CharField(max_length=2, choices=UnityChoices.choices, default='g')  # 3

    # 3 = die auswahlmögl. werden als Charfield an die variable übergeben welche durch die choices methode als choicefield gerendert wird.

    def __str__(self):
        return f'{self.value} |' \
               f'{self.currency_choice_field}' \
               f'{self.ingredients} | '

'''

templates/home/EVERY_single_pic_category_view.html
{% extends 'home/base.html' %} {% comment gibt an da wir den Code block aus home/base benutzen - so ähnlich wie vererbung von files %}{% endcomment %}
{% load static %}


{% block title %} Home - Create Your own Recipe {% endblock %}

{% block styles %}




{% endblock %}



{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'create/create.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'home/home_css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user-list-img-view/list.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'detail/detail.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'categories/style.css' %}">
{% endblock %}



{% block authForm %}
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
    {% if image|length > 0 %}

    <main class="list_view_main">
        {% for product in image %}

            <button class="category_image_container" id="single_category_image" name="single_category_image"
                    type="submit" value="{{ product.slug }}">

                <img class="pic"
                     title="{{ product.title }}"
                     src="{{ product.picture.url }}"
                     alt="{{ product.title }}">

                <span class="category_name_text"
                     title="{{ product.title }}">
                    <span style="transition-delay: .4s;">
                        {{ product.title }}
                    </span>
                </span>

            </button>

        {% endfor %}
        </main>
    {% else %}
        <main class="nothing_here_yet_container">
            <p class="nothing_here_text">
                Nothing here yet!
                <svg xmlns="http://www.w3.org/2000/svg" width="44" height="44" fill="currentColor" class="bi bi-emoji-frown" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M4.285 12.433a.5.5 0 0 0 .683-.183A3.498 3.498 0 0 1 8 10.5c1.295 0 2.426.703 3.032 1.75a.5.5 0 0 0 .866-.5A4.498 4.498 0 0 0 8 9.5a4.5 4.5 0 0 0-3.898 2.25.5.5 0 0 0 .183.683zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z"/>
                </svg>
            </p>
        </main>

    {% endif %}





</form>




{% endblock %}

templates/home/categories.html
{% extends 'home/base.html' %} {% comment gibt an da wir den Code block aus home/base benutzen - so ähnlich wie vererbung von files %}{% endcomment %}
{% load static %}


{% block title %} Categories {% endblock %}




{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'create/create.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'home/home_css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user-list-img-view/list.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'detail/detail.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'categories/style.css' %}">
{% endblock %}



{% block authForm %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <main class="list_view_main">
           {% for value in image %}

                <button class="category_image_container" type="submit" name="category_container" id="category_container"
                 value="{{ value.slug }}">


                    {% if value.p_cat_picture %}

                    <img class="pic"
                     title="{{ value.name }}"
                     src="{{ value.p_cat_picture.url }}"
                     alt="{{ value.name }}">

                    {%  else %}

                    <img class="pic"
                     title="{{ value.name }}"
                     src="{{ value.g_cat_picture.url }}"
                     alt="{{ value.name }}">

                    {%  endif %}

                    <div class="category_name_text"
                         title="{{ value.name }}">
                        <p style="transition-delay: .4s;">
                            {{ value.name }}
                        </p>
                    </div>

                </button>

            {% endfor %}
        </main>
    </form>


{% endblock %}

templates/home/edit.html
{% extends 'home/base.html' %} {% comment gibt an da wir den Code block aus home/base benutzen - so ähnlich wie vererbung von files %}{% endcomment %}
{% load static %}




{% block title %} Home - Create Your own Recipe {% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'create/create.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'home/home_css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'edit/edit.css' %}">
{% endblock %}




{% block styles %}





{% endblock %}


{% block authForm %}
<form method=POST enctype=multipart/form-data>
{% csrf_token %}
    <main class="edit_main">
        <header class="header_box">
            <div class="header_text_box">
                <h2>
                    Edit
                </h2>
            </div>
        </header>
        <section class="main_container">
            <header class="header_form_content">
                <label>
                    {{ form.title.label }}
                </label>
                {{ form.title }}
                {{ form.title.errors }}
            </header>
            <div class="image_edit_div">
                <div class="current_img_div">
                    <div class="image_container" id="trigger_image">
                        <img class="current_img" title="{{ object.title }}" src="{{ object.picture.url }}"
                          alt="{{ object.title }}" onclick="click()">
                        <svg xmlns="http://www.w3.org/2000/svg" width="160" height="160" onclick="click()" fill="currentColor" class="bi bi-card-image" viewBox="0 0 16 16">
                            <path d="M6.002 5.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                            <path d="M1.5 2A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13zm13 1a.5.5 0 0 1 .5.5v6l-3.775-1.947a.5.5 0 0 0-.577.093l-3.71 3.71-2.66-1.772a.5.5 0 0 0-.63.062L1.002 12v.54A.505.505 0 0 1 1 12.5v-9a.5.5 0 0 1 .5-.5h13z"/>
                        </svg>
                    </div>
                </div>
                <div class="select_new_img_div">
                    {{ form.picture }}
                    {{ form.picture.errors }}
                </div>
            </div>

            <div class="price_container_edit">
                <div class="price_box">
                    <label>
                        {{ form.price.label }} &nbsp;
                    </label>
                    {{ form.price }}
                    {{ form.price.errors }}
                </div>
                <div class="category_box">
                    <label>
                        {{ form.category.label }}
                    </label>
                    {{ form.category }}
                    {{ form.category.errors }}
                    {{ object.picture.url }}
                </div>

            </div>

            <div class="tag_field_container">
                <label for="tags">
                    {{ form.tag_field.label }}
                </label>
                {{ form.tag_field }}
                {{ form.tag_field.errors }}
            </div>
        </section>
        <footer class="footer_edit">
            <button class="save_changes_button" type="submit" title="submit_button" name="submit_button">
                <a>
                    save changes
                </a>
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-check" viewBox="0 0 16 16">
                    <path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z"/>
                </svg>
            </button>
        </footer>
    </main>
</form>









<script>
    document.querySelector('#trigger_image').addEventListener('click', function() {
        document.querySelector('#id_picture').click();
    });



var input = document.getElementById('id_tag_field');

// Überprüfen Sie, ob der Input-Container fokussiert ist
if (document.activeElement === input) {
    input.addEventListener('keydown', function(event) {
    if (event.key === 'Enter' || event.key === ' ' || event.key === ',') {

    }
});
} else {
    // Der Input-Container ist nicht fokussiert
    console.log('Der Input-Container ist nicht fokussiert');
}










</script>






{% endblock %}

templates/home/profile.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %} Profile {% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'create/create.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'home/home_css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user-list-img-view/list.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'detail/detail.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'profile/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'register/style.css' %}">
{% endblock %}

{% block script %}
    <script src="{% static 'profile/script.js' %}"></script>
{% endblock %}

{% block authForm %}

    <main class="main_profile">
        <section class="navbar_options">
            <nav class="profile_sidebar">
                    <ul class="element_block">
                        <li class="navigation_bar" id="change_profile_button">
                            <p>
                                Profile Settings
                            </p>
                        </li>
                        <li class="navigation_bar" id="change_password_button">
                            <p>
                                Change your Password
                            </p>
                        </li>
                        <li class="navigation_bar" onclick="window.location.href='{% url 'home:create' %}';">
                            <p>
                                Upload ans Sell
                            </p>
                        </li>
                        <li class="navigation_bar" onclick="window.location.href='{% url 'home:my-images' %}';">
                            <p>
                                My Images
                            </p>
                        </li>
                        <li class="navigation_bar" onclick="window.location.href='{% url 'home:my-images' %}';">
                            <p>
                                My Images
                            </p>
                        </li>
                        <li class="navigation_bar" onclick="window.location.href='{% url 'home:my-images' %}';">
                            <p>
                                General Settings
                            </p>
                        </li>
                        <li class="navigation_bar" onclick="window.location.href='{% url 'home:my-images' %}';">
                            <p>
                                Sign Out
                            </p>
                        </li>
                    </ul>
                </nav>
        </section>
        <section class="content_profile">
    <form method="POST">
        {% csrf_token %}
            <div class="profile_img_div">
                <img class="profile_image" src="{{ request.user.profile_image.url }}" alt="{{ request.user.username }}- profile_img"
                 onclick="document.getElementById('profile_img_id').click()">
                <span style="display: none;">
                    {{ form.profile_image }}
                </span>
                <span class="profile_img_box_shadow"></span>
            </div>

            <div class="profile_upper_body">

                <div id="first_name_container">
                    {{ form.first_name.label }}
                    {{ form.first_name }}
                </div>

                <div id="last_name_container">
                    {{ form.last_name.label }}
                    {{ form.last_name }}
                </div>
            </div>

            <div class="profile_body">
                <div style="grid-row: 2;">
                    {{ form.username.label }}
                    {{ form.username }}
                </div>

                <div style="grid-row: 4; margin-top: 60px;">
                    {{ form.email.label }}
                    {{ form.email }}
                </div>

                <div class="save_button_container">
                    <button class="universal_sexy_button" type="submit">
                            <svg width="100%" height="40px" viewBox="0 0 1200 70">
                                <polyline points="1200,1 1200,67 1,67 1,1 1200,1" class="bg-line" style="stroke-width: 2;"/>
                                <polyline points="1200,1 1200,67 1,67 1,1 1200,1" class="hl-line" style="stroke-width: 2;" />
                            </svg>
                        Save changes
                    </button>
                </div>
            </div>
            </form>

        </section>

    <section class="pw_change_page">   {% comment %} 100px 50px 110px 50px 100px; {% endcomment %}
        <form method="POST">
            {% csrf_token %}
            <header class="change_header"> {% comment %} 1 {% endcomment %}
                <h3>
                    Enter your new Password
                </h3>
            </header>

            <main class="body_pw_change"> {% comment %} 2;  {% endcomment %}


                <div style="margin-right: 10px; grid-column: 1; grid-row: 1;">
                    {{ form.password.label }}
                    {{ form.password }}
                </div>
                <div style="margin-left: 10px; grid-column: 2; grid-row: 1;">
                    <label for="#password2">
                        Confirm
                    </label>
                    <span id="password2" style="width: 100%;">
                        {{ form.password2 }}
                    </span>
                </div>

                <div class="info_text_container">
                    <p>
                        We will send you a confirmation Mail to your Email Address.
                    </p>
                </div>
            </main>
            <footer>

            </footer>
                    </form>

        </section>

    </main>















{% endblock %}



{% comment %}
profil settings uterteilung:
- persönliche Daten (pb, pw, mail, nn,)
- extra container für  gespeicherte rezepte
-
{% endcomment %}

templates/home/register.html
{% extends 'home/base.html' %} {% comment gibt an da wir den Code block aus home/base benutzen - so ähnlich wie vererbung von files %}{% endcomment %}

{% load static %}

{% block title %} Register {% endblock %}
{% block styles %}



{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'register/style.css' %}">
{% endblock %}

{% block authForm %}  {% comment Wir nehemen uns hier zunächst die block und endblock klammern aus home und cpen Sie hier rein %}{% endcomment %}

<form method="POST" enctype="multipart/form-data">
    <main class="auth_main">
        <header class="auth_header">
            <h1>
                Register
            </h1>
        </header>

        <section class="auth_profile_img_section">
            <div class="auth_profile_container">
                <img class="auth_profile_img" src="{% static 'home/home_images/user_img_default.png' %}" alt="profile_image.jpg"
                 onclick="document.getElementById('profile_img_id').click()">
                {{ form.profile_image }}
                <span class="profile_img_box_shadow"></span>
            </div>
        </section>

        <section class="auth_body">
            {% csrf_token %}

            <div class="body_row1">

                <div  style="grid-column: 1; flex-direction: column; margin-right: 15px;">
                    {{ form.first_name }}
                    {{ form.first_name.errors }}
                </div>

                <div style="grid-column: 2; flex-direction: column; margin-left: 15px;">
                    {{ form.last_name }}
                    {{ form.last_name.errors }}
                </div>
            </div>

            <div class="body_row2" style="display: flex; flex-direction: column; left: -100px;">
                {{ form.username }}
                {{ form.username.errors }}
            </div>

            <div class="body_row3" style="display: flex; flex-direction: column; ">
                {{ form.email }}
                {{ form.email.errors }}
            </div>

            <div class="body_row4" style="display: flex; flex-direction: column; ">
                {{ form.password }}
                {{ form.password.errors }}
            </div>

            <div class="body_row5" style="display: flex; flex-direction: column; ">
                {{ form.password2 }}
                {{ form.password2.errors }}
            </div>

            <div class="body_row6">
                <button class='auth_button' type="submit" id="register_button" name="register_button" title="Register">
                    Register
                </button>
            </div>

        </section>

        <footer class="auth_footer">

            <p class="login_text">
                Already have an account? <br><br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;
                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Log In here!
             </p>

            <button class="login_button"  onclick="window.location.href='{% url 'home:login' %}';">
                Login
            </button>

        </footer>

    </main>

</form>


{% endblock %}